# Generated by Django 2.2.7 on 2019-11-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFSC',
            fields=[
                ('ifsc', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ifsc')),
                ('bank_id', models.CharField(max_length=3)),
                ('branch', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
    ]
