# Generated by Django 2.2.7 on 2019-12-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifscsearch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ifscsearch',
            name='ifsc',
            field=models.CharField(max_length=30),
        ),
    ]
